apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson
  labels:
    app: python_app
spec:
  containers:
    - name: web
      image: justhynd/fast_api_expample:latest
      ports:
        - name: web
          containerPort: 8000
          protocol: TCP
